site_name: MkDocs demo doc

theme:
  name: 'material'
  font:
    text: Arial
  icon:
    repo: fontawesome/brands/github
    
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

nav: 
- Home: index.md
- API:
  - Vehicle: vehicle.md
  - Car: car.md
- Demo: 
  - Car class demo: notebooks/car_demo.ipynb

plugins:
  - mkdocstrings
  - include-markdown
  - mermaid2
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True

copyright: Created by Leo Wu in 2023

extra:
  generator: false

repo_url: https://github.com/leowu4ever/mkdocs-template
repo_name: mkdocs-template


